// Traducciones PT del catálogo i18n de la web. GENERADO por backend/generar_i18n_pt.py
// Se fusiona sobre STRINGS en i18n.js. Las claves sin PT caen a ES.
export const PT = {
  "ad.access_active_revoke": "Acesso ao relatório ativo — revogar",
  "ad.back_advisees": "← Os meus advisees",
  "ad.close_make_final": "Fechar Realizar Relatório final",
  "ad.close_manage": "Fechar gestão",
  "ad.close_manual": "Fechar manualmente",
  "ad.dl_monthly_evals": "Descarregar PDF de avaliações mensais",
  "ad.dl_opinions": "Descarregar PDF de opiniões",
  "ad.dl_personal_tracking": "Descarregar PDF de acompanhamento pessoal",
  "ad.dl_proj_evals": "Descarregar PDF de avaliações de projeto",
  "ad.edit_goals": "Editar objetivos",
  "ad.err_no_doc": "O documento não foi gerado.",
  "ad.err_save_note": "Não foi possível guardar a nota.",
  "ad.err_save_note2": "Erro ao guardar a nota.",
  "ad.generating": "A gerar...",
  "ad.give_access": "Dar acesso ao seu relatório",
  "ad.loading_history": "A carregar histórico...",
  "ad.make_final": "Realizar Relatório final",
  "ad.manage_report": "Gerir relatório",
  "ad.manual": "Manualmente",
  "ad.meetings_log": "Registo de reuniões / Comentários",
  "ad.no_notes": "Ainda não existem notas registadas.",
  "ad.note_placeholder": "Escreve aqui as tuas anotações sobre esta reunião ou qualquer comentário...",
  "ad.save_note": "Guardar nota",
  "ad.upload_final": "Carregar relatório final",
  "ad.view_available_info": "Ver informação disponível",
  "ad.view_included_evals": "Ver avaliações incluídas",
  "ad.with_claude": "Com a ajuda do Claude",
  "admin.download_word": "Descarregar Word",
  "admin.err_download": "Não foi possível descarregar o ficheiro.",
  "admin.err_load_report": "Não foi possível carregar o relatório.",
  "admin.no_final_report": "Sem relatório final disponível.",
  "admin.no_results": "Não há resultados para “{q}”.",
  "admin.reports": "Relatórios",
  "admin.search_employee": "Pesquisar colaborador",
  "admin.search_placeholder": "Escreve um nome...",
  "admin.view_final_report": "Ver relatório final",
  "aep.activate_another": "Ativar outro projeto",
  "aep.activate_n_many": "Ativar avaliações ({n} selecionados)",
  "aep.activate_n_one": "Ativar avaliações ({n} selecionado)",
  "aep.activated": "Avaliações ativadas para {n} pessoa(s). Foi-lhes enviada uma notificação pelo Slack.",
  "aep.activating": "A ativar...",
  "aep.back_home": "Voltar ao início",
  "aep.desc": "Como responsável de projeto, introduz o nome do projeto e seleciona os membros da tua equipa. Serão notificados pelo Slack e poderão aceder aos formulários de avaliação.",
  "aep.err_activate": "Não foi possível ativar.",
  "aep.err_select_employee": "Seleciona pelo menos um colaborador.",
  "aep.err_type_project": "Escreve o nome do projeto.",
  "aep.format_hint": "Formato: ANO_EMPRESA_NOME (sem espaços nem acentos, ex. 2026_Acme_Inovacao)",
  "aep.loading_employees": "A carregar colaboradores...",
  "aep.members_selected_many": "membros selecionados",
  "aep.members_selected_one": "membro selecionado",
  "aep.project_name": "Nome do projeto",
  "aep.search_by_name": "Pesquisar por nome...",
  "aep.team_members": "Membros da equipa",
  "aep.title": "Ativar avaliações",
  "auth.back_to_login": "← Voltar ao início de sessão",
  "auth.back_word": "Voltar",
  "auth.desc_forgot": "Introduz o teu email corporativo e enviar-te-emos um link para repor a tua palavra-passe.",
  "auth.desc_reset": "Escolhe uma nova palavra-passe para a tua conta.",
  "auth.err_pw_mismatch": "As palavras-passe não coincidem.",
  "auth.err_weak_pw": "A palavra-passe deve ter no mínimo 8 caracteres, uma maiúscula e um carácter especial.",
  "auth.eyebrow": "Avaliações internas",
  "auth.forgot_link": "Esqueci a minha palavra-passe",
  "auth.forgot_sent": "Se o email existir, enviámos-te um link para alterar a palavra-passe.",
  "auth.legal_1": "Ao aceder, aceita a nossa ",
  "auth.legal_2": " e os ",
  "auth.legal_3": " de utilização da plataforma.",
  "auth.legal_privacy": "política de privacidade",
  "auth.legal_terms": "termos e condições",
  "auth.password": "Palavra-passe",
  "auth.processing": "A processar...",
  "auth.pw_hint": "Mínimo 8 caracteres, uma maiúscula e um carácter especial. As palavras-passe devem coincidir.",
  "auth.pw_updated": "Palavra-passe atualizada. Já podes entrar.",
  "auth.remember": "Lembrar-me",
  "auth.repeat_pw": "Repete a palavra-passe",
  "auth.save_pw": "Guardar palavra-passe",
  "auth.send_link": "Enviar ligação",
  "auth.title_forgot": "Recuperar palavra-passe",
  "auth.title_login": "Iniciar sessão",
  "auth.title_register": "Criar conta",
  "auth.title_reset": "Nova palavra-passe",
  "auth.title_verify": "Verificação necessária",
  "auth.user": "Utilizador",
  "auth.user_or_email": "Utilizador ou email",
  "auth.verify_btn": "Verificar",
  "auth.verify_code_label": "Código de verificação",
  "auth.verify_intro_1": "Por segurança, enviámos um código de 6 dígitos para ",
  "auth.verify_intro_2": ". Introduz-o a seguir. Expira em 10 minutos.",
  "cep.already_evaluated": "Já avaliaste *{emp}* em *{proy}* nesta sessão. Diz-me o nome de outro membro.",
  "cep.area_negocio": "Negócio",
  "cep.ask_area": "A que área pertences?\n*1.* Negócio\n*2.* MiddleOffice\n*3.* Palantir",
  "cep.ask_other_member": "Perfeito. Que outro membro queres avaliar?",
  "cep.ask_other_member_proj": "Perfeito. Que outro membro do projeto *{proy}* queres avaliar?",
  "cep.ask_other_project": "Está a trabalhar nalgum outro projeto?",
  "cep.ask_project": "Escreve o nome de um dos projetos em que estás a trabalhar. Mais tarde poderás avaliar os restantes",
  "cep.ask_which_mod": "Que resposta queres modificar?\n{items}\n\nResponde com o número.",
  "cep.ask_who": "Quem pretendes avaliar? Diz-me o nome da pessoa.",
  "cep.ask_who_list": "Quem pretendes avaliar?\n{lista}",
  "cep.ask_who_short": "Quem queres avaliar? Diz-me o nome.",
  "cep.ask_whose_mod": "A avaliação de quem queres modificar?",
  "cep.btn_comenzar": "Começar",
  "cep.btn_mod_answers": "✏️ Modificar respostas",
  "cep.btn_modificar": "✏️ Modificar",
  "cep.bye": "Até breve! 👋",
  "cep.completed": "Avaliação concluída ✅",
  "cep.enter_new_answer": "Escreve a nova resposta.",
  "cep.enter_new_project": "Escreve o novo nome do projeto.",
  "cep.enter_person": "Indica o nome da pessoa a avaliar.",
  "cep.err_save": "⚠️ Não foi possível guardar no Notion. {msg}",
  "cep.err_temp": "⚠️ Erro temporário. Tenta novamente.",
  "cep.err_temp_data": "⚠️ Erro temporário ao consultar dados. Tenta novamente.",
  "cep.grace_intro": "💬 Tem avaliações recentes que pode modificar durante 2 dias após as ter guardado.\n\nCarregue em *✏️ Modificar respostas* para alterar algo.",
  "cep.mod_item_persona": "1. Pessoa avaliada",
  "cep.mod_item_proyecto": "2. Projeto",
  "cep.no": "❌ Não",
  "cep.no_questions": "⚠️ Não existem perguntas configuradas.",
  "cep.not_found": "*{nome}* não consta na lista de colaboradores. Escreva o nome e apelido tal como aparece na lista.",
  "cep.not_found2": "*{v}* não aparece na lista. Escreve o nome e apelido.",
  "cep.not_found_suggest": "*{nombre}* não consta na lista de colaboradores.\nQuerías dizer algum destes?\n{sug}",
  "cep.not_found_suggest2": "*{v}* não aparece na lista.\nQuis dizer algum destes?\n{sug}",
  "cep.pending_intro": "📍 *Tens uma avaliação mensal pendente.*\n\n_Esta avaliação é totalmente privada, apenas o CA da pessoa avaliada a poderá ver._\n_Se em algum momento quiseres cancelar, clica em Cancelar._\n\n*Clica no botão* para iniciar a avaliação.",
  "cep.ph_answer": "Escreve a tua resposta...",
  "cep.ph_field_number": "Número do campo...",
  "cep.ph_new_answer": "Nova resposta...",
  "cep.ph_or_name": "Ou escreve o nome...",
  "cep.ph_person": "Nome do colega...",
  "cep.ph_project": "Nome do projeto...",
  "cep.project_ok": "Perfeito 😊, vamos com o projeto *{val}*. Diz-me o nome de um dos membros da tua equipa, poderás avaliar os restantes depois.",
  "cep.reply_1_5": "Por favor, responde com um número de 1 a 5 🔢",
  "cep.reply_number": "Por favor, responde com um número 🔢",
  "cep.reply_number_range": "Por favor, responde com um número de 1 a {max} 🔢",
  "cep.resumen_evaluado": "- *Pessoa avaliada*: {v}",
  "cep.resumen_head": "*Resumo das tuas respostas:*",
  "cep.resumen_proyecto": "- *Projeto*: {v}",
  "cep.resumen_satisf": "\n Estás satisfeito com as tuas respostas?\nClica em *✅ Sim, guardar* ou *✏️ Modificar*.",
  "cep.save_yes": "✅ Sim, guardar",
  "cep.saved": "✅ *Avaliação guardada no Notion*.\n\nExistem mais membros na equipa que queira avaliar?",
  "cep.thanks_close": "Perfeito, muito obrigado pelo teu tempo ❤️. Já podes fechar esta secção 👋",
  "cep.thanks_grace": "Perfeito, muito obrigado pelo teu tempo ❤️\n\n💬 Se quiseres modificar as tuas respostas, tens um prazo de 2 dias.",
  "cep.updated": "✅ *Avaliação atualizada* ❤️\n\nQueres modificar a avaliação de mais alguém?",
  "cep.yes": "✅ Sim",
  "common.back": "← Voltar",
  "common.cancel": "Cancelar",
  "common.close": "Fechar",
  "common.delete": "Eliminar",
  "common.deleting": "A eliminar...",
  "common.err_generic": "Não foi possível concluir a ação.",
  "common.loading": "A carregar…",
  "common.logout": "Terminar sessão",
  "common.no_date": "Sem data",
  "common.save": "Guardar",
  "common.saving": "A guardar...",
  "common.send": "Enviar",
  "dash.annual_desc": "Gera uma base para o relatório anual de avaliações.",
  "dash.annual_generated": "Relatório anual gerado.",
  "dash.annual_report": "Relatório anual",
  "dash.annual_report_of": "Relatório anual de {nombre}",
  "dash.ca_opinion": "Opinião do CA:",
  "dash.claude_draft": "Rascunho de Claude",
  "dash.country_change": "Alterar",
  "dash.country_error": "Não foi possível guardar o país.",
  "dash.country_none": "Sem definir",
  "dash.country_placeholder": "Seleciona o teu país",
  "dash.country_saved": "País atualizado.",
  "dash.current_selection": "Seleção atual: {v}",
  "dash.download_annual": "Transferir relatório anual",
  "dash.downloading": "A descarregar o ficheiro...",
  "dash.err_download_file": "Erro ao descarregar o ficheiro.",
  "dash.evals_seen": "Avaliações vistas:",
  "dash.evaluated_person": "Pessoa avaliada",
  "dash.file_ready": "Ficheiro pronto.",
  "dash.final_ca": "Versão final CA",
  "dash.final_report": "Relatório final",
  "dash.final_report_of": "Relatório final de {nombre}",
  "dash.gen_annual": "Gerar relatório anual",
  "dash.gen_report": "O Claude está a gerar o relatório...",
  "dash.interpreting": "O Claude está a interpretar o texto do avaliador...",
  "dash.manage_evals": "Gestão de avaliações",
  "dash.my_country": "O meu país",
  "dash.my_goals": "Os meus objetivos",
  "dash.my_reports": "Os meus relatórios",
  "dash.my_role": "A minha função",
  "dash.nav_activate_proj": "Ativar avaliações de projeto",
  "dash.nav_admin_panel": "Painel de administração",
  "dash.nav_manage_projects": "Gerir os meus projetos ativos",
  "dash.nav_my_advisees": "Os meus advisees",
  "dash.nav_proj_evals": "Avaliações por projetos",
  "dash.no_access": "Não há relatórios disponíveis.",
  "dash.no_final_report": "Não há relatório final disponível.",
  "dash.no_goals": "Sem objetivos definidos.",
  "dash.no_opinions": "Não há opiniões guardadas sobre {nombre}.",
  "dash.no_table": "sem tabela disponível",
  "dash.open_web": "Abrir na web",
  "dash.open_web_short": "Abrir na web",
  "dash.open_web_version": "Abrir versão web",
  "dash.opinions_about": "Opiniões sobre {nombre}",
  "dash.report_ready": "Relatório pronto com {n} avaliações.",
  "dash.result": "Resultado",
  "dash.select_person": "Seleciona uma pessoa avaliada.",
  "eaw.all_confirmed": "Todas as áreas confirmadas",
  "eaw.area_n": "Área {i}/{total}",
  "eaw.confirm_area": "Confirmar área e continuar →",
  "eaw.confirm_identity_q": "É esta a pessoa que vais avaliar?",
  "eaw.draft_desc": "Abre-o, preenche os espaços (notas/retribuição) e carrega-o como relatório final.",
  "eaw.draft_done": "Rascunho gerado ✓",
  "eaw.err_start": "Não foi possível iniciar a avaliação.",
  "eaw.err_write_points": "Escreve os teus pontos antes de enviar.",
  "eaw.eyebrow": "Avaliação anual assistida",
  "eaw.full_info": "Informação completa",
  "eaw.gen_draft": "Gerar rascunho",
  "eaw.generating": "A gerar…",
  "eaw.info_considered": "Informação que a IA considerou desta área ({n})",
  "eaw.loading_area": "A carregar área…",
  "eaw.no_back": "Não, voltar",
  "eaw.no_evidence": "Sem evidência específica para esta área.",
  "eaw.ph_main_points": "Os teus pontos principais e a tua opinião…",
  "eaw.ph_respond_ai": "Responde à IA…",
  "eaw.respond": "Responder",
  "eaw.review_areas": "Rever áreas",
  "eaw.send_to_ai": "Enviar à IA",
  "eaw.sending": "A enviar…",
  "eaw.summary_desc": "No final, a IA preenche o rascunho com o acordado em cada área (deixando os espaços de notas/retribuição em branco para que os completes e o carregues).",
  "eaw.view_draft": "Ver rascunho",
  "eaw.year_projects": "Projetos do ano: {list}",
  "eaw.year_stat": "Ano {anio} · {done}/{total} áreas confirmadas",
  "eaw.yes_correct_start": "Sim, está correto · começar",
  "ep.completed": "Concluída",
  "ep.fill_eval": "Preencher avaliação",
  "ep.history": "Histórico",
  "ep.kicker": "Avaliação de projeto",
  "ep.pending": "Pendente",
  "ep.progress": "Progresso das avaliações",
  "ep.progress_stat": "{done} de {total} concluídas · {pct}%",
  "ep.project_label": "Projeto",
  "ep.section_auto": "Autoavaliação",
  "ep.section_manager": "Avaliações ao manager",
  "ep.section_members": "Avaliações aos membros",
  "ess.editable": "Modificável",
  "ess.intro": "Responder aqui é exatamente igual a responder no Slack. As tuas respostas são guardadas no mesmo sítio e no mesmo formato.",
  "ess.page_kicker": "Avaliações no Slack",
  "ess.select_type": "Seleciona um tipo de avaliação.",
  "ess.soon_short": "Próx.",
  "ess.tab_monthly": "Avaliação mensal",
  "ess.tab_personal": "Avaliação pessoal",
  "ess.tip_done": "Já concluíste esta avaliação no ciclo atual",
  "ess.tip_editable": "Podes modificar as tuas respostas (margem de 2 dias)",
  "ess.tip_soon": "Em breve",
  "fep.err_required": "Por favor responde todas as perguntas obrigatórias.",
  "fep.err_save": "Não foi possível guardar.",
  "fep.err_select_person": "Seleciona a pessoa a avaliar.",
  "fep.evaluating": "A avaliar: {nombre}",
  "fep.evaluating_self": "A avaliar-te a ti próprio: {nombre}",
  "fep.label_auto": "Autoavaliação",
  "fep.label_manager": "Avaliação ao responsável",
  "fep.label_member": "Avaliação a membro",
  "fep.label_peer": "Avaliação a colega",
  "fep.loading_questions": "A carregar perguntas...",
  "fep.new_eval": "Nova avaliação",
  "fep.no_questions": "Não existem perguntas configuradas para este tipo de avaliação.",
  "fep.person_to_eval": "Pessoa a avaliar",
  "fep.saved_notion": "Avaliação guardada corretamente no Notion.",
  "fep.saved_ok": "Avaliação guardada corretamente.",
  "fep.scale_high": "5 — Cumpre totalmente",
  "fep.scale_low": "1 — Não cumpre",
  "fep.select_dash": "— Seleciona —",
  "fep.submit": "Enviar avaliação",
  "footer.privacy": "Privacidade",
  "footer.terms": "Termos",
  "goals.add_another": "+ Adicionar outro",
  "goals.confirm_delete": "Eliminar este objetivo?",
  "goals.desc_label": "Descrição",
  "goals.desc_ph": "Detalha como trabalhar este objetivo...",
  "goals.history": "Histórico",
  "goals.kicker": "Objetivos",
  "goals.kpis_field_label": "KPIs para o seu cumprimento",
  "goals.kpis_ph": "Ex: Apresentar em 2 reuniões de cliente por trimestre",
  "goals.new": "Novo objetivo",
  "goals.none_for": "Não há objetivos para {nome}.",
  "goals.of_person": "Objetivos de {nome}",
  "goals.remove_aria": "Remover objetivo",
  "goals.save_many": "Guardar {n} objetivos",
  "goals.save_one": "Guardar objetivo",
  "goals.saved_many": "{n} objetivos guardados corretamente.",
  "goals.saved_one": "Objetivo guardado corretamente.",
  "goals.title_label": "Título *",
  "goals.title_ph": "Ex: Melhorar competências de apresentação",
  "goals.type_label": "Tipo",
  "goals.type_ph": "Ex: Desenvolvimento pessoal, Técnico, Liderança...",
  "hist.col_date": "Data",
  "hist.col_justif": "Justificação",
  "hist.col_relation": "Relação",
  "hist.col_score": "Avaliação",
  "hist.empty": "Ainda não tens avaliações registadas para este projeto.",
  "hist.err_load": "Não foi possível carregar as avaliações.",
  "hist.project_label": "Projeto:",
  "hist.rel_equal": "Igual",
  "hist.rel_lower": "Inferior",
  "hist.rel_superior": "Superior",
  "hist.title": "Histórico de avaliações",
  "legal.privacy_title": "Política de privacidade",
  "legal.terms_title": "Termos e condições",
  "legal.unavailable": "Documento não disponível.",
  "mpa.add": "Adicionar",
  "mpa.add_member": "+ Adicionar membro",
  "mpa.col_member": "Membro",
  "mpa.col_received": "Recebidas",
  "mpa.col_selfeval": "Autoavaliação",
  "mpa.col_status": "Estado",
  "mpa.complete": "Concluído",
  "mpa.err_modify": "Erro ao modificar.",
  "mpa.evaluated_by": "Avaliado por: {list}",
  "mpa.kicker": "Gestão de projeto",
  "mpa.loading_state": "A carregar estado das avaliações...",
  "mpa.member_added": "{emp} adicionado.",
  "mpa.member_removed": "{emp} eliminado.",
  "mpa.no_data": "Sem dados de avaliação ainda.",
  "mpa.no_projects": "Não tens projetos com avaliações ativas.",
  "mpa.pending": "Pendente",
  "mpa.pending_from": "Pendente de: {list}",
  "mpa.pending_from_count": "Pendente de {n} pessoa(s)",
  "mpa.progress": "{done} de {total} avaliações concluídas",
  "mpa.rec_button": "Enviar lembrete à equipa",
  "mpa.rec_err": "Não foi possível enviar o lembrete.",
  "mpa.rec_none": "Ninguém tem avaliações pendentes neste projeto. 🎉",
  "mpa.rec_sending": "A enviar...",
  "mpa.rec_sent": "Lembrete enviado a {n} pessoa(s) com avaliações pendentes.",
  "mpa.remove_member": "Eliminar {nombre}",
  "mpa.select_person": "Seleciona uma pessoa...",
  "mpa.title": "Os meus projetos ativos",
  "obj.kpis_label": "KPIs:",
  "obj.my_goals_title": "Os meus objetivos.",
  "obj.none_yet": "Ainda não tens objetivos registados.",
  "obj.personal_dev": "Desenvolvimento pessoal",
  "pw.hide": "Ocultar palavra-passe",
  "pw.show": "Mostrar palavra-passe",
  "role.admin_desc": "Consulta avaliações e relatórios de qualquer colaborador",
  "role.admin_title": "Administrador",
  "role.how_enter": "Como queres entrar hoje?",
  "role.personal_desc": "Acede como qualquer outro colaborador da empresa",
  "role.personal_title": "Perfil pessoal",
  "role.welcome": "Bem-vindo",
  "subir.current_desc": "Já existe um relatório final carregado. Pode transferi-lo ou carregar um novo para o substituir.",
  "subir.current_version": "Versão atual",
  "subir.err_upload": "Não foi possível carregar o relatório.",
  "subir.upload_btn": "Carregar relatório",
  "subir.upload_desc": "Carregue o Word com a sua versão final. É guardado no Notion e o advisee poderá transferi-lo. São mantidas as 2 versões mais recentes.",
  "subir.upload_final": "Carregar versão final",
  "subir.uploaded": "Relatório carregado",
  "subir.uploaded_ok": "Relatório carregado com sucesso.",
  "subir.uploading": "A carregar relatório...",
  "subir.uploading_btn": "A carregar...",
  "subir.word_file": "Ficheiro Word (.docx)"
};
